#! /bin/sh

sxhkd &

# Wallpaper
feh --randomize --bg-fill ~/customization/wallpapers/current &

# lemonbar
~/customization/status/run_bar.sh &

# window shadow and opacity
# compton -r 2 -o 0.5 -l 2 -t 2

# Because I'm in this for the aesthetics
bspc config border_width         2
bspc config window_gap          20

# For lemonbar
bspc config top_padding         14

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Colors
bspc config normal_border_color   "#f8f8f2"
bspc config focused_border_color  "#f92672"
bspc config presel_feedback_color "#f92672"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a feh floating=on manage=off

# https://github.com/baskerville/bspwm/issues/143
bspc monitor -d 1 2 3 4

