#! /bin/sh

setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

sxhkd &

picom --backend glx --experimental-backends --blur-method dual_kawase --blur-strength 10 &

polybar system &
polybar system_ext &

# wal -R &

feh -r --bg-fill /home/jtao/customization/wallpapers/current &

# Desktops
bspc monitor eDP-1 -d {m1,m2,m3,m4}
bspc monitor DP-1  -d {e1,e2,e3,e4}
# bspc monitor -d {西,南,北,東}

# A e s t h e t i c s
bspc config border_width         2
bspc config window_gap           8
bspc config top_padding		 40

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Per-program configs
bpsc rule -a dmenu_extended_run floating=on
bspc rule -a zoom state=floating center=on follow=on border=off
bspc rule -a NoiseTorth state=floating border=off

# Set colors from wal
# . "${HOME}/.cache/wal/colors.sh"
# bspc config normal_border_color "$background"
# bspc config focused_border_color "$foreground"
# bspc config presel_feedback_color "$color1"

# Colors
bspc config normal_border_color  "#4C566A"
bspc config focused_border_color "#ECEFF4"
bspc config presel_feedback_color "#88C0D0"

